global:
  scrape_interval: 15s
  evaluation_interval: 1m
  external_labels:
    stack: otel-collector-platform

rule_files:
  - /etc/prometheus/platform-rules/*.yml
  - /etc/prometheus/producer-rules/*.yml

scrape_configs:
  - job_name: otel-signals
    static_configs:
      - targets: ["otel-collector:9464"]
  - job_name: otel-collector-internal
    static_configs:
      - targets: ["otel-collector:8888"]
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

